### ISSUE TITLE
Drop support for unsupported frameworks

### ISSUE THREAD

**Issue by ghost1face** [ForcuraCo/npi-api-net#8]
`net5`  `netstandard1.5` `netcoreapp2.1`

**Comment by ghost1face** [comment]
We'll look to perform this in the next major version update

**Comment by tiesont** [comment]
Given this:

> We are not going to support .NET 6 with Visual Studio 2019. This decision will not be changed. You need to use Visual Studio 2022 for .NET 6. I appreciate that some companies have not upgraded to that version.

https://github.com/dotnet/core/issues/5567#issuecomment-1105996161

Would it make sense to update the .sln file's `VisualStudioVersion` and `MinimumVisualStudioVersion` to `17.0.31903.59`, the build version of the first Release version of Visual Studio 17 (aka Visual Studio 2022)?

netstandard2.0 does include .NET5, if I recall correctly, but if we're really trying to make .NET6 the minimum, it probably makes sense to enforce a minimum build environment that matches.

**Comment by ghost1face** [comment]
Yeah that's probably best, we can upgrade the solution file
